import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import jsdoc from "eslint-plugin-jsdoc";

export default [
    js.configs.recommended,
    ...tseslint.configs.recommended,
    jsdoc.configs["flat/recommended-typescript-error"],
    {
        files: ["**/*.{js,mjs,cjs,ts,tsx,mts,cts}"],
        plugins: {
            jsdoc,
        },
        languageOptions: {
            globals: globals.browser,
        },
        rules: {
            "jsdoc/check-access": 2,
            "jsdoc/check-alignment": 2,
            "jsdoc/check-indentation": 2,
            "jsdoc/check-line-alignment": 2,
            "jsdoc/check-param-names": 2,
            "jsdoc/check-template-names": 2,
            "jsdoc/check-property-names": 2,
            "jsdoc/check-syntax": 2,
            "jsdoc/check-tag-names": 2,
            "jsdoc/check-types": 2,
            "jsdoc/check-values": 2,
            "jsdoc/empty-tags": 2,
            "jsdoc/implements-on-classes": 2,
            "jsdoc/multiline-blocks": 2,
            "jsdoc/no-bad-blocks": 2,
            "jsdoc/no-blank-block-descriptions": 2,
            "jsdoc/no-defaults": 2,
            "jsdoc/no-multi-asterisks": 2,
            "jsdoc/no-types": 2,
            "jsdoc/no-undefined-types": 2,
            "jsdoc/require-asterisk-prefix": 2,
            "jsdoc/require-description": 2,
            "jsdoc/require-description-complete-sentence": 2,
            "jsdoc/require-hyphen-before-param-description": 2,
            "jsdoc/require-jsdoc": 2,
            "jsdoc/require-param": 2,
            "jsdoc/require-param-description": 2,
            "jsdoc/require-param-name": 2,
            "jsdoc/require-property": 2,
            "jsdoc/require-property-description": 2,
            "jsdoc/require-property-name": 2,
            "jsdoc/require-returns": 2,
            "jsdoc/require-returns-check": 2,
            "jsdoc/require-returns-description": 2,
            "jsdoc/require-template": 2,
            "jsdoc/require-throws": 2,
            "jsdoc/require-yields": 2,
            "jsdoc/require-yields-check": 2,
            "jsdoc/sort-tags": 2,
            "jsdoc/tag-lines": 2,
            "jsdoc/valid-types": 2,
        },
    },
];
