#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 Claude Code PM - Simplified Workflow"
echo "========================================"
echo ""
echo "🚀 Quick Start - One Command Automation"
echo "  /pm:task-auto \"<task>\" --execute"
echo ""
echo "  ⚡ Fast, simple, and powerful"
echo "  ⚡ Single GitHub issue per task"
echo "  ⚡ Automatic parallel execution"
echo ""
echo "---"
echo ""
echo "📋 Task Commands (Step-by-Step)"
echo "  /pm:task-auto \"<desc>\" [--depth <level>] [--execute]"
echo "                             - Full automation (recommended)"
echo "  /pm:task-explore \"<desc>\" [--depth light|medium|deep]"
echo "                             - Explore codebase for task"
echo "  /pm:task-plan <task-id>    - Generate execution plan from exploration"
echo "  /pm:task-create <task-id>  - Create GitHub issue with plan"
echo "  /pm:task-execute <issue#>  - Execute plan with parallel agents"
echo ""
echo "📝 Issue Commands"
echo "  /pm:issue-show <num>      - Display issue details"
echo "  /pm:issue-status <num>    - Check issue status"
echo "  /pm:issue-start <num>     - Begin work with specialized agent"
echo "  /pm:issue-sync <num>      - Push updates to GitHub"
echo "  /pm:issue-close <num>     - Mark issue as complete"
echo "  /pm:issue-reopen <num>    - Reopen closed issue"
echo "  /pm:issue-edit <num>      - Edit issue details"
echo "  /pm:issue-analyze <num>   - Analyze for parallel work streams"
echo ""
echo "🔄 Workflow Commands"
echo "  /pm:next               - Show next priority tasks"
echo "  /pm:status             - Overall project dashboard"
echo "  /pm:standup            - Daily standup report"
echo "  /pm:blocked            - Show blocked tasks"
echo "  /pm:in-progress        - List work in progress"
echo ""
echo "🔗 Sync Commands"
echo "  /pm:sync               - Full bidirectional sync with GitHub"
echo "  /pm:import <issue>     - Import existing GitHub issues"
echo ""
echo "🔧 Maintenance Commands"
echo "  /pm:validate           - Check system integrity"
echo "  /pm:clean              - Archive completed work"
echo "  /pm:search <query>     - Search across all content"
echo ""
echo "⚙️  Setup Commands"
echo "  /pm:init               - Install dependencies and configure GitHub"
echo "  /pm:help               - Show this help message"
echo ""
echo "💡 Quick Examples"
echo "  # Full automation"
echo "  /pm:task-auto \"Add dark mode toggle\" --execute"
echo ""
echo "  # Step-by-step"
echo "  /pm:task-explore \"Add dark mode toggle\""
echo "  /pm:task-plan <task-id>"
echo "  /pm:task-create <task-id>"
echo "  /pm:task-execute <issue-number>"
echo ""
echo "  # Deep exploration for complex tasks"
echo "  /pm:task-auto \"Refactor auth system\" --depth deep --execute"
echo ""
echo "💡 Tips"
echo "  • Use /pm:task-auto for quick automation"
echo "  • Use /pm:next to find available work"
echo "  • Run /pm:status for quick overview"
echo "  • View .claude/tasks/README.md for documentation"
echo "  • Workflow: explore → plan → create → execute"

exit 0
